### ISSUE TITLE
运行NaiveBayes遇到一个问题

### ISSUE THREAD

**Issue by luciferaaa** [htshinichi/ML_model#1]
没有改动源代码，下载后运行发现如下异常信息

C:\Anaconda3\envs\python.exe C:/MachineLearn/ML_model-master/NaiveBayes/DATA_NB_test.py
Traceback (most recent call last):
  File "C:\Anaconda3\envs\lib\site-packages\pandas\core\indexes\base.py", line 2442, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5280)
  File "pandas\_libs\index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5126)
  File "pandas\_libs\hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20523)
  File "pandas\_libs\hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20477)
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/MachineLearn/ML_model-master/NaiveBayes/DATA_NB_test.py", line 16, in <module>
    model_NBC.getPredictions(dia_train,dia_test)
  File "C:\MachineLearn\ML_model-master\NaiveBayes\NaiveBayesContinuous.py", line 72, in getPredictions
    result,proby = self.predict(TrainData,self.testdata[i])
  File "C:\MachineLearn\ML_model-master\NaiveBayes\NaiveBayesContinuous.py", line 54, in predict
    self.cmean,self.cstd,self.label_array=self.getMeanStdLabel(trainData)
  File "C:\MachineLearn\ML_model-master\NaiveBayes\NaiveBayesContinuous.py", line 29, in getMeanStdLabel
    names['mc%s' % j].append(np.mean(names['c%s' % j][k]))
  File "C:\Anaconda3\envs\lib\site-packages\pandas\core\frame.py", line 1964, in __getitem__
    return self._getitem_column(key)
  File "C:\Anaconda3\envs\lib\site-packages\pandas\core\frame.py", line 1971, in _getitem_column
    return self._get_item_cache(key)
  File "C:\Anaconda3\envs\lib\site-packages\pandas\core\generic.py", line 1645, in _get_item_cache
    values = self._data.get(item)
  File "C:\Anaconda3\envs\lib\site-packages\pandas\core\internals.py", line 3590, in get
    loc = self.items.get_loc(item)
  File "C:\Anaconda3\envs\lib\site-packages\pandas\core\indexes\base.py", line 2444, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5280)
  File "pandas\_libs\index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5126)
  File "pandas\_libs\hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20523)
  File "pandas\_libs\hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20477)
KeyError: 0

Process finished with exit code 1

**Comment by luciferaaa** [comment]
可以修改下
 names['mc%s' % j].append(np.mean(names['c%s' % j]['%s' % k]))
names['sc%s' % j].append(np.std(names['c%s' % j]['%s' % k], ddof=1))
